### ISSUE TITLE
Ogg stream stops palying when song change if there is metadata on it

### ISSUE THREAD

**Issue by giflw** [pdudits/soundlibs#4]
Hi

I was trying to play a ogg stream. When track changes, if there is metadata on the stream, next track is not played. If there are no metadata on the stream, playing goes well.

**Comment by pdudits** [comment]
Hi,

the libraries are not maintained actively over here, the main concern is having them on Maven Central. However, if you manage to find a fix for your issue, I'd happilly accept a PR.

**Comment by giflw** [comment]
Hi

I'll try to fix that. It's almost a year that I'm trying to understand the bug. Now I'll try to find a solution. As soon I find, I'll open a PR.

Thanks

**Comment by giflw** [comment]
In the past, I've used the JavaTunes player and it worked fine. The owner has published the core in https://github.com/stigc/JavaTunes-Audio-Player. It worked fine for me.
